package at.sljivic.aegis

import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import java.io.File
import java.util.concurrent.TimeUnit

/**
 * Executes an external command (executable) using ProcessBuilder.
 * @param executablePath The path to the executable file.
 * @param args The arguments to pass to the executable.
 * @param timeoutSeconds The maximum time to wait for the process to finish.
 * @return A Pair containing the exit code and the captured output (or error).
 */
fun executeExecutable(
        executablePath: String,
        args: List<String> = emptyList(),
        timeoutSeconds: Long = 60
): Pair<Int, String> {
    // 1. Combine the executable path and its arguments into a single list of command parts
    val commandParts = mutableListOf(executablePath).apply { addAll(args) }

    // 2. Create and configure the ProcessBuilder
    val process =
            try {
                ProcessBuilder(commandParts)
                        .directory(
                                File(".")
                        ) // Optional: Set the working directory (defaults to current dir)
                        .redirectErrorStream(false) // Merges stdout and stderr into one stream
                        .start()
            } catch (e: Exception) {
                // Handle file not found, permission denied, etc.
                return Pair(-1, "Error starting process: ${e.message}")
            }

    // 3. Wait for the process to finish
    val finished = process.waitFor(timeoutSeconds, TimeUnit.SECONDS)

    if (!finished) {
        // Process did not finish within the timeout
        process.destroyForcibly()
        return Pair(-2, "Process timed out after $timeoutSeconds seconds.")
    }

    // 4. Capture the output
    val output = process.inputStream.bufferedReader().use { it.readText() }
    val exitCode = process.exitValue()

    // 5. Return the result
    return Pair(exitCode, output.trim())
}

val x64_linux_syscall_num_to_name =
        arrayOf(
                "read",
                "write",
                "open",
                "close",
                "stat",
                "fstat",
                "lstat",
                "poll",
                "lseek",
                "mmap",
                "mprotect",
                "munmap",
                "brk",
                "rt_sigaction",
                "rt_sigprocmask",
                "rt_sigreturn",
                "ioctl",
                "pread64",
                "pwrite64",
                "readv",
                "writev",
                "access",
                "pipe",
                "select",
                "sched_yield",
                "mremap",
                "msync",
                "mincore",
                "madvise",
                "shmget",
                "shmat",
                "shmctl",
                "dup",
                "dup2",
                "pause",
                "nanosleep",
                "getitimer",
                "alarm",
                "setitimer",
                "getpid",
                "sendfile",
                "socket",
                "connect",
                "accept",
                "sendto",
                "recvfrom",
                "sendmsg",
                "recvmsg",
                "shutdown",
                "bind",
                "listen",
                "getsockname",
                "getpeername",
                "socketpair",
                "setsockopt",
                "getsockopt",
                "clone",
                "fork",
                "vfork",
                "execve",
                "exit",
                "wait4",
                "kill",
                "uname",
                "semget",
                "semop",
                "semctl",
                "shmdt",
                "msgget",
                "msgsnd",
                "msgrcv",
                "msgctl",
                "fcntl",
                "flock",
                "fsync",
                "fdatasync",
                "truncate",
                "ftruncate",
                "getdents",
                "getcwd",
                "chdir",
                "fchdir",
                "rename",
                "mkdir",
                "rmdir",
                "creat",
                "link",
                "unlink",
                "symlink",
                "readlink",
                "chmod",
                "fchmod",
                "chown",
                "fchown",
                "lchown",
                "umask",
                "gettimeofday",
                "getrlimit",
                "getrusage",
                "sysinfo",
                "times",
                "ptrace",
                "getuid",
                "syslog",
                "getgid",
                "setuid",
                "setgid",
                "geteuid",
                "getegid",
                "setpgid",
                "getppid",
                "getpgrp",
                "setsid",
                "setreuid",
                "setregid",
                "getgroups",
                "setgroups",
                "setresuid",
                "getresuid",
                "setresgid",
                "getresgid",
                "getpgid",
                "setfsuid",
                "setfsgid",
                "getsid",
                "capget",
                "capset",
                "rt_sigpending",
                "rt_sigtimedwait",
                "rt_sigqueueinfo",
                "rt_sigsuspend",
                "sigaltstack",
                "utime",
                "mknod",
                "uselib",
                "personality",
                "ustat",
                "statfs",
                "fstatfs",
                "sysfs",
                "getpriority",
                "setpriority",
                "sched_setparam",
                "sched_getparam",
                "sched_setscheduler",
                "sched_getscheduler",
                "sched_get_priority_max",
                "sched_get_priority_min",
                "sched_rr_get_interval",
                "mlock",
                "munlock",
                "mlockall",
                "munlockall",
                "vhangup",
                "modify_ldt",
                "pivot_root",
                "_sysctl",
                "prctl",
                "arch_prctl",
                "adjtimex",
                "setrlimit",
                "chroot",
                "sync",
                "acct",
                "settimeofday",
                "mount",
                "umount2",
                "swapon",
                "swapoff",
                "reboot",
                "sethostname",
                "setdomainname",
                "iopl",
                "ioperm",
                "create_module",
                "init_module",
                "delete_module",
                "get_kernel_syms",
                "query_module",
                "quotactl",
                "nfsservctl",
                "getpmsg",
                "putpmsg",
                "afs_syscall",
                "tuxcall",
                "security",
                "gettid",
                "readahead",
                "setxattr",
                "lsetxattr",
                "fsetxattr",
                "getxattr",
                "lgetxattr",
                "fgetxattr",
                "listxattr",
                "llistxattr",
                "flistxattr",
                "removexattr",
                "lremovexattr",
                "fremovexattr",
                "tkill",
                "time",
                "futex",
                "sched_setaffinity",
                "sched_getaffinity",
                "set_thread_area",
                "io_setup",
                "io_destroy",
                "io_getevents",
                "io_submit",
                "io_cancel",
                "get_thread_area",
                "lookup_dcookie",
                "epoll_create",
                "epoll_ctl_old",
                "epoll_wait_old",
                "remap_file_pages",
                "getdents64",
                "set_tid_address",
                "restart_syscall",
                "semtimedop",
                "fadvise64",
                "timer_create",
                "timer_settime",
                "timer_gettime",
                "timer_getoverrun",
                "timer_delete",
                "clock_settime",
                "clock_gettime",
                "clock_getres",
                "clock_nanosleep",
                "exit_group",
                "epoll_wait",
                "epoll_ctl",
                "tgkill",
                "utimes",
                "vserver",
                "mbind",
                "set_mempolicy",
                "get_mempolicy",
                "mq_open",
                "mq_unlink",
                "mq_timedsend",
                "mq_timedreceive",
                "mq_notify",
                "mq_getsetattr",
                "kexec_load",
                "waitid",
                "add_key",
                "request_key",
                "keyctl",
                "ioprio_set",
                "ioprio_get",
                "inotify_init",
                "inotify_add_watch",
                "inotify_rm_watch",
                "migrate_pages",
                "openat",
                "mkdirat",
                "mknodat",
                "fchownat",
                "futimesat",
                "newfstatat",
                "unlinkat",
                "renameat",
                "linkat",
                "symlinkat",
                "readlinkat",
                "fchmodat",
                "faccessat",
                "pselect6",
                "ppoll",
                "unshare",
                "set_robust_list",
                "get_robust_list",
                "splice",
                "tee",
                "sync_file_range",
                "vmsplice",
                "move_pages",
                "utimensat",
                "epoll_pwait",
                "signalfd",
                "timerfd_create",
                "eventfd",
                "fallocate",
                "timerfd_settime",
                "timerfd_gettime",
                "accept4",
                "signalfd4",
                "eventfd2",
                "epoll_create1",
                "dup3",
                "pipe2",
                "inotify_init1",
                "preadv",
                "pwritev",
                "rt_tgsigqueueinfo",
                "perf_event_open",
                "recvmmsg",
                "fanotify_init",
                "fanotify_mark",
                "prlimit64",
                "name_to_handle_at",
                "open_by_handle_at",
                "clock_adjtime",
                "syncfs",
                "sendmmsg",
                "setns",
                "getcpu",
                "process_vm_readv",
                "process_vm_writev",
                "kcmp",
                "finit_module",
                "sched_setattr",
                "sched_getattr",
                "renameat2",
                "seccomp",
                "getrandom",
                "memfd_create",
                "kexec_file_load",
                "bpf",
                "execveat",
                "userfaultfd",
                "membarrier",
                "mlock2",
                "copy_file_range",
                "preadv2",
                "pwritev2",
                "pkey_mprotect",
                "pkey_alloc",
                "pkey_free",
                "statx",
                "io_pgetevents",
                "rseq",
                "uretprobe",
                "pidfd_send_signal",
                "io_uring_setup",
                "io_uring_enter",
                "io_uring_register",
                "open_tree",
                "move_mount",
                "fsopen",
                "fsconfig",
                "fsmount",
                "fspick",
                "pidfd_open",
                "clone3",
                "close_range",
                "openat2",
                "pidfd_getfd",
                "faccessat2",
                "process_madvise",
                "epoll_pwait2",
                "mount_setattr",
                "quotactl_fd",
                "landlock_create_ruleset",
                "landlock_add_rule",
                "landlock_restrict_self",
                "memfd_secret",
                "process_mrelease",
                "futex_waitv",
                "set_mempolicy_home_node",
                "cachestat",
                "fchmodat2",
                "map_shadow_stack",
                "futex_wake",
                "futex_wait",
                "futex_requeue",
                "statmount",
                "listmount",
                "lsm_get_self_attr",
                "lsm_set_self_attr",
                "lsm_list_modules",
                "mseal",
                "setxattrat",
                "getxattrat",
                "listxattrat",
                "removexattrat",
                "open_tree_attr"
        )

fun get_syscall_list(): ArrayList<String> {
    val executable = "/tmp/HackaTUM/tracer" // For Unix-like systems (Linux/macOS)
    // val executable = "cmd.exe" // Use "cmd.exe" for Windows
    val arguments = listOf("ls", ".")

    println("Executing command: $executable ${arguments.joinToString(" ")}")

    val (code, output) = executeExecutable(executable, arguments)

    println("\n--- Execution Result ---")
    println("Exit Code: $code")
    println("Output:")
    println(output)
    println("------------------------")

    val nums = output.split("\n")
    var syscall_names_in_order = ArrayList<String>()
    for (num in nums) {
        //   println("to int: $num");
        val intNum = num.toInt()
        val syscall_name = x64_linux_syscall_num_to_name.get(intNum)
        println("Syscall was: $syscall_name")
        syscall_names_in_order.add(syscall_name)
    }
    return syscall_names_in_order
}

fun main() = application {
    Window(
            onCloseRequest = ::exitApplication,
            title = "aegis",
    ) {
        App()
        println(get_syscall_list())
    }
}
