package at.sljivic.aegis

import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import java.io.File
import java.util.concurrent.TimeUnit

/**
 * Executes an external command (executable) using ProcessBuilder.
 * @param executablePath The path to the executable file.
 * @param args The arguments to pass to the executable.
 * @param timeoutSeconds The maximum time to wait for the process to finish.
 * @return A Pair containing the exit code and the captured output (or error).
 */
fun executeExecutable(
        executablePath: String,
        args: List<String> = emptyList(),
        timeoutSeconds: Long = 60
): Pair<Int, String> {
    // 1. Combine the executable path and its arguments into a single list of command parts
    val commandParts = mutableListOf(executablePath).apply { addAll(args) }

    // 2. Create and configure the ProcessBuilder
    val process =
            try {
                ProcessBuilder(commandParts)
                        .directory(
                                File(".")
                        ) // Optional: Set the working directory (defaults to current dir)
                        .redirectErrorStream(false) // Merges stdout and stderr into one stream
                        .start()
            } catch (e: Exception) {
                // Handle file not found, permission denied, etc.
                return Pair(-1, "Error starting process: ${e.message}")
            }

    // 3. Wait for the process to finish
    val finished = process.waitFor(timeoutSeconds, TimeUnit.SECONDS)

    if (!finished) {
        // Process did not finish within the timeout
        process.destroyForcibly()
        return Pair(-2, "Process timed out after $timeoutSeconds seconds.")
    }

    // 4. Capture the output
    val output = process.inputStream.bufferedReader().use { it.readText() }
    val exitCode = process.exitValue()

    // 5. Return the result
    return Pair(exitCode, output.trim())
}

val x64_linux_syscall_num_to_name =
        arrayOf(
                Syscall("read", OperationType.File),
                Syscall("write", OperationType.File),
                Syscall("open", OperationType.File),
                Syscall("close", OperationType.File),
                Syscall("stat", OperationType.File),
                Syscall("fstat", OperationType.File),
                Syscall("lstat", OperationType.Unclassified),
                Syscall("poll", OperationType.File),
                Syscall("lseek", OperationType.Unclassified),
                Syscall("mmap", OperationType.Unclassified),
                Syscall("mprotect", OperationType.Unclassified),
                Syscall("munmap", OperationType.Unclassified),
                Syscall("brk", OperationType.Unclassified),
                Syscall("rt_sigaction", OperationType.Unclassified),
                Syscall("rt_sigprocmask", OperationType.Unclassified),
                Syscall("rt_sigreturn", OperationType.Unclassified),
                Syscall("ioctl", OperationType.Unclassified),
                Syscall("pread64", OperationType.Unclassified),
                Syscall("pwrite64", OperationType.Unclassified),
                Syscall("readv", OperationType.Unclassified),
                Syscall("writev", OperationType.Unclassified),
                Syscall("access", OperationType.Unclassified),
                Syscall("pipe", OperationType.Unclassified),
                Syscall("select", OperationType.Unclassified),
                Syscall("sched_yield", OperationType.Unclassified),
                Syscall("mremap", OperationType.Unclassified),
                Syscall("msync", OperationType.Unclassified),
                Syscall("mincore", OperationType.Unclassified),
                Syscall("madvise", OperationType.Unclassified),
                Syscall("shmget", OperationType.Unclassified),
                Syscall("shmat", OperationType.Unclassified),
                Syscall("shmctl", OperationType.Unclassified),
                Syscall("dup", OperationType.Unclassified),
                Syscall("dup2", OperationType.Unclassified),
                Syscall("pause", OperationType.Unclassified),
                Syscall("nanosleep", OperationType.Unclassified),
                Syscall("getitimer", OperationType.Unclassified),
                Syscall("alarm", OperationType.Unclassified),
                Syscall("setitimer", OperationType.Unclassified),
                Syscall("getpid", OperationType.Unclassified),
                Syscall("sendfile", OperationType.Unclassified),
                Syscall("socket", OperationType.Unclassified),
                Syscall("connect", OperationType.Unclassified),
                Syscall("accept", OperationType.Unclassified),
                Syscall("sendto", OperationType.Unclassified),
                Syscall("recvfrom", OperationType.Unclassified),
                Syscall("sendmsg", OperationType.Unclassified),
                Syscall("recvmsg", OperationType.Unclassified),
                Syscall("shutdown", OperationType.Unclassified),
                Syscall("bind", OperationType.Unclassified),
                Syscall("listen", OperationType.Unclassified),
                Syscall("getsockname", OperationType.Unclassified),
                Syscall("getpeername", OperationType.Unclassified),
                Syscall("socketpair", OperationType.Unclassified),
                Syscall("setsockopt", OperationType.Unclassified),
                Syscall("getsockopt", OperationType.Unclassified),
                Syscall("clone", OperationType.Unclassified),
                Syscall("fork", OperationType.Unclassified),
                Syscall("vfork", OperationType.Unclassified),
                Syscall("execve", OperationType.Unclassified),
                Syscall("exit", OperationType.Unclassified),
                Syscall("wait4", OperationType.Unclassified),
                Syscall("kill", OperationType.Unclassified),
                Syscall("uname", OperationType.Unclassified),
                Syscall("semget", OperationType.Unclassified),
                Syscall("semop", OperationType.Unclassified),
                Syscall("semctl", OperationType.Unclassified),
                Syscall("shmdt", OperationType.Unclassified),
                Syscall("msgget", OperationType.Unclassified),
                Syscall("msgsnd", OperationType.Unclassified),
                Syscall("msgrcv", OperationType.Unclassified),
                Syscall("msgctl", OperationType.Unclassified),
                Syscall("fcntl", OperationType.Unclassified),
                Syscall("flock", OperationType.Unclassified),
                Syscall("fsync", OperationType.Unclassified),
                Syscall("fdatasync", OperationType.Unclassified),
                Syscall("truncate", OperationType.Unclassified),
                Syscall("ftruncate", OperationType.Unclassified),
                Syscall("getdents", OperationType.Unclassified),
                Syscall("getcwd", OperationType.Unclassified),
                Syscall("chdir", OperationType.Unclassified),
                Syscall("fchdir", OperationType.Unclassified),
                Syscall("rename", OperationType.Unclassified),
                Syscall("mkdir", OperationType.Unclassified),
                Syscall("rmdir", OperationType.Unclassified),
                Syscall("creat", OperationType.Unclassified),
                Syscall("link", OperationType.Unclassified),
                Syscall("unlink", OperationType.Unclassified),
                Syscall("symlink", OperationType.Unclassified),
                Syscall("readlink", OperationType.Unclassified),
                Syscall("chmod", OperationType.Unclassified),
                Syscall("fchmod", OperationType.Unclassified),
                Syscall("chown", OperationType.Unclassified),
                Syscall("fchown", OperationType.Unclassified),
                Syscall("lchown", OperationType.Unclassified),
                Syscall("umask", OperationType.Unclassified),
                Syscall("gettimeofday", OperationType.Unclassified),
                Syscall("getrlimit", OperationType.Unclassified),
                Syscall("getrusage", OperationType.Unclassified),
                Syscall("sysinfo", OperationType.Unclassified),
                Syscall("times", OperationType.Unclassified),
                Syscall("ptrace", OperationType.Unclassified),
                Syscall("getuid", OperationType.Unclassified),
                Syscall("syslog", OperationType.Unclassified),
                Syscall("getgid", OperationType.Unclassified),
                Syscall("setuid", OperationType.Unclassified),
                Syscall("setgid", OperationType.Unclassified),
                Syscall("geteuid", OperationType.Unclassified),
                Syscall("getegid", OperationType.Unclassified),
                Syscall("setpgid", OperationType.Unclassified),
                Syscall("getppid", OperationType.Unclassified),
                Syscall("getpgrp", OperationType.Unclassified),
                Syscall("setsid", OperationType.Unclassified),
                Syscall("setreuid", OperationType.Unclassified),
                Syscall("setregid", OperationType.Unclassified),
                Syscall("getgroups", OperationType.Unclassified),
                Syscall("setgroups", OperationType.Unclassified),
                Syscall("setresuid", OperationType.Unclassified),
                Syscall("getresuid", OperationType.Unclassified),
                Syscall("setresgid", OperationType.Unclassified),
                Syscall("getresgid", OperationType.Unclassified),
                Syscall("getpgid", OperationType.Unclassified),
                Syscall("setfsuid", OperationType.Unclassified),
                Syscall("setfsgid", OperationType.Unclassified),
                Syscall("getsid", OperationType.Unclassified),
                Syscall("capget", OperationType.Unclassified),
                Syscall("capset", OperationType.Unclassified),
                Syscall("rt_sigpending", OperationType.Unclassified),
                Syscall("rt_sigtimedwait", OperationType.Unclassified),
                Syscall("rt_sigqueueinfo", OperationType.Unclassified),
                Syscall("rt_sigsuspend", OperationType.Unclassified),
                Syscall("sigaltstack", OperationType.Unclassified),
                Syscall("utime", OperationType.Unclassified),
                Syscall("mknod", OperationType.Unclassified),
                Syscall("uselib", OperationType.Unclassified),
                Syscall("personality", OperationType.Unclassified),
                Syscall("ustat", OperationType.Unclassified),
                Syscall("statfs", OperationType.Unclassified),
                Syscall("fstatfs", OperationType.Unclassified),
                Syscall("sysfs", OperationType.Unclassified),
                Syscall("getpriority", OperationType.Unclassified),
                Syscall("setpriority", OperationType.Unclassified),
                Syscall("sched_setparam", OperationType.Unclassified),
                Syscall("sched_getparam", OperationType.Unclassified),
                Syscall("sched_setscheduler", OperationType.Unclassified),
                Syscall("sched_getscheduler", OperationType.Unclassified),
                Syscall("sched_get_priority_max", OperationType.Unclassified),
                Syscall("sched_get_priority_min", OperationType.Unclassified),
                Syscall("sched_rr_get_interval", OperationType.Unclassified),
                Syscall("mlock", OperationType.Unclassified),
                Syscall("munlock", OperationType.Unclassified),
                Syscall("mlockall", OperationType.Unclassified),
                Syscall("munlockall", OperationType.Unclassified),
                Syscall("vhangup", OperationType.Unclassified),
                Syscall("modify_ldt", OperationType.Unclassified),
                Syscall("pivot_root", OperationType.Unclassified),
                Syscall("_sysctl", OperationType.Unclassified),
                Syscall("prctl", OperationType.Unclassified),
                Syscall("arch_prctl", OperationType.Unclassified),
                Syscall("adjtimex", OperationType.Unclassified),
                Syscall("setrlimit", OperationType.Unclassified),
                Syscall("chroot", OperationType.Unclassified),
                Syscall("sync", OperationType.Unclassified),
                Syscall("acct", OperationType.Unclassified),
                Syscall("settimeofday", OperationType.Unclassified),
                Syscall("mount", OperationType.Unclassified),
                Syscall("umount2", OperationType.Unclassified),
                Syscall("swapon", OperationType.Unclassified),
                Syscall("swapoff", OperationType.Unclassified),
                Syscall("reboot", OperationType.Unclassified),
                Syscall("sethostname", OperationType.Unclassified),
                Syscall("setdomainname", OperationType.Unclassified),
                Syscall("iopl", OperationType.Unclassified),
                Syscall("ioperm", OperationType.Unclassified),
                Syscall("create_module", OperationType.Unclassified),
                Syscall("init_module", OperationType.Unclassified),
                Syscall("delete_module", OperationType.Unclassified),
                Syscall("get_kernel_syms", OperationType.Unclassified),
                Syscall("query_module", OperationType.Unclassified),
                Syscall("quotactl", OperationType.Unclassified),
                Syscall("nfsservctl", OperationType.Unclassified),
                Syscall("getpmsg", OperationType.Unclassified),
                Syscall("putpmsg", OperationType.Unclassified),
                Syscall("afs_syscall", OperationType.Unclassified),
                Syscall("tuxcall", OperationType.Unclassified),
                Syscall("security", OperationType.Unclassified),
                Syscall("gettid", OperationType.Unclassified),
                Syscall("readahead", OperationType.Unclassified),
                Syscall("setxattr", OperationType.Unclassified),
                Syscall("lsetxattr", OperationType.Unclassified),
                Syscall("fsetxattr", OperationType.Unclassified),
                Syscall("getxattr", OperationType.Unclassified),
                Syscall("lgetxattr", OperationType.Unclassified),
                Syscall("fgetxattr", OperationType.Unclassified),
                Syscall("listxattr", OperationType.Unclassified),
                Syscall("llistxattr", OperationType.Unclassified),
                Syscall("flistxattr", OperationType.Unclassified),
                Syscall("removexattr", OperationType.Unclassified),
                Syscall("lremovexattr", OperationType.Unclassified),
                Syscall("fremovexattr", OperationType.Unclassified),
                Syscall("tkill", OperationType.Unclassified),
                Syscall("time", OperationType.Unclassified),
                Syscall("futex", OperationType.Unclassified),
                Syscall("sched_setaffinity", OperationType.Unclassified),
                Syscall("sched_getaffinity", OperationType.Unclassified),
                Syscall("set_thread_area", OperationType.Unclassified),
                Syscall("io_setup", OperationType.Unclassified),
                Syscall("io_destroy", OperationType.Unclassified),
                Syscall("io_getevents", OperationType.Unclassified),
                Syscall("io_submit", OperationType.Unclassified),
                Syscall("io_cancel", OperationType.Unclassified),
                Syscall("get_thread_area", OperationType.Unclassified),
                Syscall("lookup_dcookie", OperationType.Unclassified),
                Syscall("epoll_create", OperationType.Unclassified),
                Syscall("epoll_ctl_old", OperationType.Unclassified),
                Syscall("epoll_wait_old", OperationType.Unclassified),
                Syscall("remap_file_pages", OperationType.Unclassified),
                Syscall("getdents64", OperationType.Unclassified),
                Syscall("set_tid_address", OperationType.Unclassified),
                Syscall("restart_syscall", OperationType.Unclassified),
                Syscall("semtimedop", OperationType.Unclassified),
                Syscall("fadvise64", OperationType.Unclassified),
                Syscall("timer_create", OperationType.Unclassified),
                Syscall("timer_settime", OperationType.Unclassified),
                Syscall("timer_gettime", OperationType.Unclassified),
                Syscall("timer_getoverrun", OperationType.Unclassified),
                Syscall("timer_delete", OperationType.Unclassified),
                Syscall("clock_settime", OperationType.Unclassified),
                Syscall("clock_gettime", OperationType.Unclassified),
                Syscall("clock_getres", OperationType.Unclassified),
                Syscall("clock_nanosleep", OperationType.Unclassified),
                Syscall("exit_group", OperationType.Unclassified),
                Syscall("epoll_wait", OperationType.Unclassified),
                Syscall("epoll_ctl", OperationType.Unclassified),
                Syscall("tgkill", OperationType.Unclassified),
                Syscall("utimes", OperationType.Unclassified),
                Syscall("vserver", OperationType.Unclassified),
                Syscall("mbind", OperationType.Unclassified),
                Syscall("set_mempolicy", OperationType.Unclassified),
                Syscall("get_mempolicy", OperationType.Unclassified),
                Syscall("mq_open", OperationType.Unclassified),
                Syscall("mq_unlink", OperationType.Unclassified),
                Syscall("mq_timedsend", OperationType.Unclassified),
                Syscall("mq_timedreceive", OperationType.Unclassified),
                Syscall("mq_notify", OperationType.Unclassified),
                Syscall("mq_getsetattr", OperationType.Unclassified),
                Syscall("kexec_load", OperationType.Unclassified),
                Syscall("waitid", OperationType.Unclassified),
                Syscall("add_key", OperationType.Unclassified),
                Syscall("request_key", OperationType.Unclassified),
                Syscall("keyctl", OperationType.Unclassified),
                Syscall("ioprio_set", OperationType.Unclassified),
                Syscall("ioprio_get", OperationType.Unclassified),
                Syscall("inotify_init", OperationType.Unclassified),
                Syscall("inotify_add_watch", OperationType.Unclassified),
                Syscall("inotify_rm_watch", OperationType.Unclassified),
                Syscall("migrate_pages", OperationType.Unclassified),
                Syscall("openat", OperationType.Unclassified),
                Syscall("mkdirat", OperationType.Unclassified),
                Syscall("mknodat", OperationType.Unclassified),
                Syscall("fchownat", OperationType.Unclassified),
                Syscall("futimesat", OperationType.Unclassified),
                Syscall("newfstatat", OperationType.Unclassified),
                Syscall("unlinkat", OperationType.Unclassified),
                Syscall("renameat", OperationType.Unclassified),
                Syscall("linkat", OperationType.Unclassified),
                Syscall("symlinkat", OperationType.Unclassified),
                Syscall("readlinkat", OperationType.Unclassified),
                Syscall("fchmodat", OperationType.Unclassified),
                Syscall("faccessat", OperationType.Unclassified),
                Syscall("pselect6", OperationType.Unclassified),
                Syscall("ppoll", OperationType.Unclassified),
                Syscall("unshare", OperationType.Unclassified),
                Syscall("set_robust_list", OperationType.Unclassified),
                Syscall("get_robust_list", OperationType.Unclassified),
                Syscall("splice", OperationType.Unclassified),
                Syscall("tee", OperationType.Unclassified),
                Syscall("sync_file_range", OperationType.Unclassified),
                Syscall("vmsplice", OperationType.Unclassified),
                Syscall("move_pages", OperationType.Unclassified),
                Syscall("utimensat", OperationType.Unclassified),
                Syscall("epoll_pwait", OperationType.Unclassified),
                Syscall("signalfd", OperationType.Unclassified),
                Syscall("timerfd_create", OperationType.Unclassified),
                Syscall("eventfd", OperationType.Unclassified),
                Syscall("fallocate", OperationType.Unclassified),
                Syscall("timerfd_settime", OperationType.Unclassified),
                Syscall("timerfd_gettime", OperationType.Unclassified),
                Syscall("accept4", OperationType.Unclassified),
                Syscall("signalfd4", OperationType.Unclassified),
                Syscall("eventfd2", OperationType.Unclassified),
                Syscall("epoll_create1", OperationType.Unclassified),
                Syscall("dup3", OperationType.Unclassified),
                Syscall("pipe2", OperationType.Unclassified),
                Syscall("inotify_init1", OperationType.Unclassified),
                Syscall("preadv", OperationType.Unclassified),
                Syscall("pwritev", OperationType.Unclassified),
                Syscall("rt_tgsigqueueinfo", OperationType.Unclassified),
                Syscall("perf_event_open", OperationType.Unclassified),
                Syscall("recvmmsg", OperationType.Unclassified),
                Syscall("fanotify_init", OperationType.Unclassified),
                Syscall("fanotify_mark", OperationType.Unclassified),
                Syscall("prlimit64", OperationType.Unclassified),
                Syscall("name_to_handle_at", OperationType.Unclassified),
                Syscall("open_by_handle_at", OperationType.Unclassified),
                Syscall("clock_adjtime", OperationType.Unclassified),
                Syscall("syncfs", OperationType.Unclassified),
                Syscall("sendmmsg", OperationType.Unclassified),
                Syscall("setns", OperationType.Unclassified),
                Syscall("getcpu", OperationType.Unclassified),
                Syscall("process_vm_readv", OperationType.Unclassified),
                Syscall("process_vm_writev", OperationType.Unclassified),
                Syscall("kcmp", OperationType.Unclassified),
                Syscall("finit_module", OperationType.Unclassified),
                Syscall("sched_setattr", OperationType.Unclassified),
                Syscall("sched_getattr", OperationType.Unclassified),
                Syscall("renameat2", OperationType.Unclassified),
                Syscall("seccomp", OperationType.Unclassified),
                Syscall("getrandom", OperationType.Unclassified),
                Syscall("memfd_create", OperationType.Unclassified),
                Syscall("kexec_file_load", OperationType.Unclassified),
                Syscall("bpf", OperationType.Unclassified),
                Syscall("execveat", OperationType.Unclassified),
                Syscall("userfaultfd", OperationType.Unclassified),
                Syscall("membarrier", OperationType.Unclassified),
                Syscall("mlock2", OperationType.Unclassified),
                Syscall("copy_file_range", OperationType.Unclassified),
                Syscall("preadv2", OperationType.Unclassified),
                Syscall("pwritev2", OperationType.Unclassified),
                Syscall("pkey_mprotect", OperationType.Unclassified),
                Syscall("pkey_alloc", OperationType.Unclassified),
                Syscall("pkey_free", OperationType.Unclassified),
                Syscall("statx", OperationType.Unclassified),
                Syscall("io_pgetevents", OperationType.Unclassified),
                Syscall("rseq", OperationType.Unclassified),
                Syscall("uretprobe", OperationType.Unclassified),
                Syscall("pidfd_send_signal", OperationType.Unclassified),
                Syscall("io_uring_setup", OperationType.Unclassified),
                Syscall("io_uring_enter", OperationType.Unclassified),
                Syscall("io_uring_register", OperationType.Unclassified),
                Syscall("open_tree", OperationType.Unclassified),
                Syscall("move_mount", OperationType.Unclassified),
                Syscall("fsopen", OperationType.Unclassified),
                Syscall("fsconfig", OperationType.Unclassified),
                Syscall("fsmount", OperationType.Unclassified),
                Syscall("fspick", OperationType.Unclassified),
                Syscall("pidfd_open", OperationType.Unclassified),
                Syscall("clone3", OperationType.Unclassified),
                Syscall("close_range", OperationType.Unclassified),
                Syscall("openat2", OperationType.Unclassified),
                Syscall("pidfd_getfd", OperationType.Unclassified),
                Syscall("faccessat2", OperationType.Unclassified),
                Syscall("process_madvise", OperationType.Unclassified),
                Syscall("epoll_pwait2", OperationType.Unclassified),
                Syscall("mount_setattr", OperationType.Unclassified),
                Syscall("quotactl_fd", OperationType.Unclassified),
                Syscall("landlock_create_ruleset", OperationType.Unclassified),
                Syscall("landlock_add_rule", OperationType.Unclassified),
                Syscall("landlock_restrict_self", OperationType.Unclassified),
                Syscall("memfd_secret", OperationType.Unclassified),
                Syscall("process_mrelease", OperationType.Unclassified),
                Syscall("futex_waitv", OperationType.Unclassified),
                Syscall("set_mempolicy_home_node", OperationType.Unclassified),
                Syscall("cachestat", OperationType.Unclassified),
                Syscall("fchmodat2", OperationType.Unclassified),
                Syscall("map_shadow_stack", OperationType.Unclassified),
                Syscall("futex_wake", OperationType.Unclassified),
                Syscall("futex_wait", OperationType.Unclassified),
                Syscall("futex_requeue", OperationType.Unclassified),
                Syscall("statmount", OperationType.Unclassified),
                Syscall("listmount", OperationType.Unclassified),
                Syscall("lsm_get_self_attr", OperationType.Unclassified),
                Syscall("lsm_set_self_attr", OperationType.Unclassified),
                Syscall("lsm_list_modules", OperationType.Unclassified),
                Syscall("mseal", OperationType.Unclassified),
                Syscall("setxattrat", OperationType.Unclassified),
                Syscall("getxattrat", OperationType.Unclassified),
                Syscall("listxattrat", OperationType.Unclassified),
                Syscall("removexattrat", OperationType.Unclassified),
                Syscall("open_tree_attr", OperationType.Unclassified)
        )

actual fun getSyscallList(): ArrayList<Syscall> {
    val executable = "/tmp/HackaTUM/tracer" // For Unix-like systems (Linux/macOS)
    // val executable = "cmd.exe" // Use "cmd.exe" for Windows
    val arguments = listOf("ls", ".")

    println("Executing command: $executable ${arguments.joinToString(" ")}")

    val (code, output) = executeExecutable(executable, arguments)

    println("\n--- Execution Result ---")
    println("Exit Code: $code")
    println("Output:")
    println(output)
    println("------------------------")

    val nums = output.split("\n")
    var syscalls_in_order = ArrayList<Syscall>()
    for (num in nums) {
        //   println("to int: $num");
        val intNum = num.toInt()
        val syscall = x64_linux_syscall_num_to_name.get(intNum)
        // println("Syscall was: $syscall")
        syscalls_in_order.add(syscall)
    }
    return syscalls_in_order
}

fun main() = application {
    Window(
            onCloseRequest = ::exitApplication,
            title = "aegis",
    ) {
        App()
    }
}
